version: "3.7"
services:

  postgres:
    container_name: postgres
    ports:
      - 5434:5432
    build: ./postgres
    volumes:
      # Backup Volume
            - ./postgres/12.2/volumes/backups:/home/backups
            # Database Volume
            - ./postgres/12.2/volumes/data:/var/lib/postgresql/data
          # restart: always

  metabase:
    container_name: metabase
    restart: always
    ports:
      - 3001:3000
    build: ./metabase
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - ./metabase/metabase-data:/metabase-data
    depends_on:
      - postgres
    links:
      - postgres:postgres